// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBvDYcsXtGo5Qtfy6eQxu-5g-1i0FeBhY',
    appId: '1:1006487071210:web:02132402053258038aaa93',
    messagingSenderId: '1006487071210',
    projectId: 'party-bread',
    authDomain: 'party-bread.firebaseapp.com',
    databaseURL: 'https://party-bread-default-rtdb.firebaseio.com',
    storageBucket: 'party-bread.firebasestorage.app',
    measurementId: 'G-C9HYXG1H6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx5kGNlEheIqOk-hm0S0BRvy-ayvpgGVk',
    appId: '1:1006487071210:android:e6dec7067ff962268aaa93',
    messagingSenderId: '1006487071210',
    projectId: 'party-bread',
    databaseURL: 'https://party-bread-default-rtdb.firebaseio.com',
    storageBucket: 'party-bread.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1VDe3BIDEqqesz5oW6izHehiPfh9YTnM',
    appId: '1:1006487071210:ios:c288989d861ab9878aaa93',
    messagingSenderId: '1006487071210',
    projectId: 'party-bread',
    databaseURL: 'https://party-bread-default-rtdb.firebaseio.com',
    storageBucket: 'party-bread.firebasestorage.app',
    androidClientId:
        '1006487071210-gub9qgjmslni662vqee2ar4839ehp7bk.apps.googleusercontent.com',
    iosClientId:
        '1006487071210-eeqmlgkjrp2ph5pkk25k9h514ue7msr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.party_bread',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1VDe3BIDEqqesz5oW6izHehiPfh9YTnM',
    appId: '1:1006487071210:ios:c288989d861ab9878aaa93',
    messagingSenderId: '1006487071210',
    projectId: 'party-bread',
    databaseURL: 'https://party-bread-default-rtdb.firebaseio.com',
    storageBucket: 'party-bread.firebasestorage.app',
    androidClientId:
        '1006487071210-gub9qgjmslni662vqee2ar4839ehp7bk.apps.googleusercontent.com',
    iosClientId:
        '1006487071210-eeqmlgkjrp2ph5pkk25k9h514ue7msr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.party_bread',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBvDYcsXtGo5Qtfy6eQxu-5g-1i0FeBhY',
    appId: '1:1006487071210:web:ec853b8507fa5c608aaa93',
    messagingSenderId: '1006487071210',
    projectId: 'party-bread',
    authDomain: 'party-bread.firebaseapp.com',
    databaseURL: 'https://party-bread-default-rtdb.firebaseio.com',
    storageBucket: 'party-bread.firebasestorage.app',
    measurementId: 'G-1Q0K2SW1RV',
  );
}
